/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DriveLayoutRouteImport } from './routes/drive/_layout'
import { Route as DriveLayoutHomeRouteImport } from './routes/drive/_layout/home'
import { Route as DriveLayoutFileRouteImport } from './routes/drive/_layout/file'
import { Route as DriveLayoutSplatRouteImport } from './routes/drive/_layout/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveLayoutRoute = DriveLayoutRouteImport.update({
  id: '/drive/_layout',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveLayoutHomeRoute = DriveLayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DriveLayoutRoute,
} as any)
const DriveLayoutFileRoute = DriveLayoutFileRouteImport.update({
  id: '/file',
  path: '/file',
  getParentRoute: () => DriveLayoutRoute,
} as any)
const DriveLayoutSplatRoute = DriveLayoutSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DriveLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drive': typeof DriveLayoutRouteWithChildren
  '/drive/$': typeof DriveLayoutSplatRoute
  '/drive/file': typeof DriveLayoutFileRoute
  '/drive/home': typeof DriveLayoutHomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drive': typeof DriveLayoutRouteWithChildren
  '/drive/$': typeof DriveLayoutSplatRoute
  '/drive/file': typeof DriveLayoutFileRoute
  '/drive/home': typeof DriveLayoutHomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drive/_layout': typeof DriveLayoutRouteWithChildren
  '/drive/_layout/$': typeof DriveLayoutSplatRoute
  '/drive/_layout/file': typeof DriveLayoutFileRoute
  '/drive/_layout/home': typeof DriveLayoutHomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/drive' | '/drive/$' | '/drive/file' | '/drive/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/drive' | '/drive/$' | '/drive/file' | '/drive/home'
  id:
    | '__root__'
    | '/'
    | '/drive/_layout'
    | '/drive/_layout/$'
    | '/drive/_layout/file'
    | '/drive/_layout/home'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DriveLayoutRoute: typeof DriveLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive/_layout': {
      id: '/drive/_layout'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive/_layout/home': {
      id: '/drive/_layout/home'
      path: '/home'
      fullPath: '/drive/home'
      preLoaderRoute: typeof DriveLayoutHomeRouteImport
      parentRoute: typeof DriveLayoutRoute
    }
    '/drive/_layout/file': {
      id: '/drive/_layout/file'
      path: '/file'
      fullPath: '/drive/file'
      preLoaderRoute: typeof DriveLayoutFileRouteImport
      parentRoute: typeof DriveLayoutRoute
    }
    '/drive/_layout/$': {
      id: '/drive/_layout/$'
      path: '/$'
      fullPath: '/drive/$'
      preLoaderRoute: typeof DriveLayoutSplatRouteImport
      parentRoute: typeof DriveLayoutRoute
    }
  }
}

interface DriveLayoutRouteChildren {
  DriveLayoutSplatRoute: typeof DriveLayoutSplatRoute
  DriveLayoutFileRoute: typeof DriveLayoutFileRoute
  DriveLayoutHomeRoute: typeof DriveLayoutHomeRoute
}

const DriveLayoutRouteChildren: DriveLayoutRouteChildren = {
  DriveLayoutSplatRoute: DriveLayoutSplatRoute,
  DriveLayoutFileRoute: DriveLayoutFileRoute,
  DriveLayoutHomeRoute: DriveLayoutHomeRoute,
}

const DriveLayoutRouteWithChildren = DriveLayoutRoute._addFileChildren(
  DriveLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DriveLayoutRoute: DriveLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
